### ISSUE TITLE
Admin views not working on my install

### ISSUE THREAD

**Issue by hcharley** [datadesk/django-project-template#15]
I probably missed something obvious. I'm on Django 1.8.7

```
[08/Dec/2015 14:13:38] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 94349
[08/Dec/2015 14:13:40] "GET /login HTTP/1.1" 404 12618
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/cbodkin/.virtualenvs/newsletters.latimes.com/lib/python2.7/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/Users/cbodkin/.virtualenvs/newsletters.latimes.com/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/Users/cbodkin/.virtualenvs/newsletters.latimes.com/lib/python2.7/site-packages/debug_toolbar/panels/profiling.py", line 170, in generate_stats
    root = FunctionCall(self.stats, self.stats.get_root_func(), depth=0)
  File "/Users/cbodkin/.virtualenvs/newsletters.latimes.com/lib/python2.7/site-packages/debug_toolbar/panels/profiling.py", line 51, in __init__
    self.stats = statobj.stats[func][:4]
KeyError: None
```

**Comment by anthonyjpesce** [comment]
I"ve disabled debug toolbar by default now in settings_dev. It's constantly problematic, and I'm over it.
